"use strict";

const canvas = document.getElementById("gameCanvas");
const ctx = canvas.getContext("2d");
const W = canvas.width, H = canvas.height;
const $ = id => document.getElementById(id);
const ui = { station: $("stationValue"), scrap: $("scrapValue"), health: $("healthText"), healthFill: $("healthFill"), timer: $("timerValue"), phase: $("phaseLabel"), drone: $("droneLevel"), pulse: $("pulseButton"), pulseCooldown: $("pulseCooldown"), objective: $("objectiveText"), combo: $("comboText"), toast: $("toast"), hint: $("touchHint"), start: $("startScreen"), stationScreen: $("stationScreen"), stationTitle: $("stationTitle"), upgrades: $("upgradeList"), continue: $("continueButton"), result: $("resultScreen") };
const TAU = Math.PI * 2;
const upgrades = [
  { id: "railgun", icon: "⌁", name: "磁轨炮", desc: "列车前端发射穿透弹，每 1.1 秒一次。", cost: 30 },
  { id: "swarm", icon: "✣", name: "蜂群协议", desc: "无人机火力 +35%，击破时有概率再分裂一枚弹。", cost: 42 },
  { id: "armor", icon: "⬢", name: "装甲铆接", desc: "列车最大完整度 +25%，受到伤害降低 18%。", cost: 48 }
];
const state = { mode: "menu", station: 1, timer: 22, maxTrainHp: 100, trainHp: 100, scrap: 0, kills: 0, combo: 0, bestCombo: 0, score: 0, droneLevel: 1, fireClock: 0, spawnClock: 0, pulseClock: 0, railClock: 0, hurtFlash: 0, shake: 0, pointer: { x: 240, y: 360 }, drone: { x: 240, y: 330, tx: 240, ty: 330 }, train: { x: 195, y: 515 }, enemies: [], shots: [], particles: [], motes: [], texts: [], selectedUpgrade: null, modules: [] };

function resetRun() { Object.assign(state, { mode: "combat", station: 1, timer: 22, maxTrainHp: 100, trainHp: 100, scrap: 0, kills: 0, combo: 0, bestCombo: 0, score: 0, droneLevel: 1, fireClock: 0, spawnClock: .2, pulseClock: 0, railClock: 0, hurtFlash: 0, shake: 0, enemies: [], shots: [], particles: [], motes: [], texts: [], selectedUpgrade: null, modules: [] }); ui.start.hidden = true; ui.stationScreen.hidden = true; ui.result.hidden = true; ui.hint.style.opacity = .8; spawnWave(); updateHud(); }
function spawnWave() { const count = 5 + state.station * 2; for (let i = 0; i < count; i++) spawnEnemy(i * .14); }
function spawnEnemy(delay = 0) { const a = Math.random() * TAU, radius = 255 + Math.random() * 50; const elite = Math.random() < .1 * state.station; const regularHp = 2 + (state.station - 1) * .28; state.enemies.push({ x: 195 + Math.cos(a) * radius, y: 350 + Math.sin(a) * radius * .65, r: elite ? 19 : 13 + Math.random() * 3, hp: elite ? 5 + state.station : regularHp, maxHp: elite ? 5 + state.station : regularHp, speed: elite ? 17 : 21 + Math.random() * 11, hue: Math.random(), elite, delay, hit: 0, dead: false }); }
function update(dt) {
  if (state.mode !== "combat") return;
  state.timer -= dt; state.fireClock -= dt; state.spawnClock -= dt; state.pulseClock = Math.max(0, state.pulseClock - dt); state.railClock += dt; state.hurtFlash = Math.max(0, state.hurtFlash - dt); state.shake = Math.max(0, state.shake - dt * 20);
  state.drone.x += (state.drone.tx - state.drone.x) * Math.min(1, dt * 10); state.drone.y += (state.drone.ty - state.drone.y) * Math.min(1, dt * 10);
  if (state.spawnClock <= 0 && state.enemies.filter(e => !e.dead).length < 10) { spawnEnemy(); state.spawnClock = Math.max(.8, 1.45 - state.station * .1); }
  for (const e of state.enemies) { if (e.dead || e.delay > 0) { e.delay -= dt; continue; } const dx = state.train.x - e.x, dy = state.train.y - e.y, d = Math.hypot(dx, dy) || 1; e.x += dx / d * e.speed * dt; e.y += dy / d * e.speed * dt; e.hit = Math.max(0, e.hit - dt * 5); if (d < 42) { const damage = (e.elite ? 12 : 7) * (state.modules.includes("armor") ? .82 : 1); e.dead = true; state.trainHp = Math.max(0, state.trainHp - damage); state.hurtFlash = .3; state.shake = 5; burst(e.x, e.y, "#f16d63", 9, 60); addText("-" + Math.ceil(damage), state.train.x, state.train.y - 34, "#f16d63"); } }
  if (state.fireClock <= 0) { fireAtNearest(); state.fireClock = Math.max(.18, .42 - state.droneLevel * .035); }
  if (state.modules.includes("railgun") && state.railClock > 1.1) { fireRailgun(); state.railClock = 0; }
  updateShots(dt); updateParticles(dt);
  if (state.trainHp <= 0) finish(false); else if (state.timer <= 0) arriveStation();
  updateHud();
}
function fireAtNearest() { const targets = state.enemies.filter(e => !e.dead && e.delay <= 0); if (!targets.length) return; targets.sort((a, b) => Math.hypot(a.x - state.drone.x, a.y - state.drone.y) - Math.hypot(b.x - state.drone.x, b.y - state.drone.y)); const t = targets[0]; const a = Math.atan2(t.y - state.drone.y, t.x - state.drone.x); state.shots.push({ x: state.drone.x, y: state.drone.y, vx: Math.cos(a) * 390, vy: Math.sin(a) * 390, life: 1, target: t, color: state.droneLevel > 1 ? "#ffb45f" : "#5de1df" }); burst(state.drone.x, state.drone.y, "#5de1df", 2, 25); }
function fireRailgun() { const targets = state.enemies.filter(e => !e.dead && e.delay <= 0); if (!targets.length) return; targets.sort((a, b) => a.y - b.y); const t = targets[0]; const a = Math.atan2(t.y - (state.train.y - 28), t.x - state.train.x); state.shots.push({ x: state.train.x, y: state.train.y - 28, vx: Math.cos(a) * 510, vy: Math.sin(a) * 510, life: 1.2, target: t, color: "#ffb45f", railgun: true }); burst(state.train.x, state.train.y - 28, "#ffb45f", 7, 50); }
function updateShots(dt) { for (let i = state.shots.length - 1; i >= 0; i--) { const s = state.shots[i]; s.x += s.vx * dt; s.y += s.vy * dt; s.life -= dt; let hit = false; for (const e of state.enemies) { if (e.dead || e.delay > 0 || s.hitIds?.includes(e)) continue; if (Math.hypot(e.x - s.x, e.y - s.y) < e.r + 6) { e.hp -= s.railgun ? 2.2 : (state.modules.includes("swarm") ? 1.35 : 1); e.hit = 1; s.hitIds ||= []; s.hitIds.push(e); burst(s.x, s.y, e.elite ? "#ffb45f" : "#b6e36b", 5, 44); hit = !s.railgun; if (e.hp <= 0) killEnemy(e); if (hit) break; } } if (hit || s.life <= 0) state.shots.splice(i, 1); } }
function killEnemy(e) { e.dead = true; state.kills++; state.combo++; state.bestCombo = Math.max(state.bestCombo, state.combo); state.scrap += e.elite ? 14 : 6; state.score += (e.elite ? 130 : 50) * Math.max(1, state.combo); state.shake = e.elite ? 7 : 2; addText("+" + (e.elite ? 14 : 6), e.x, e.y - 15, "#ffb45f"); burst(e.x, e.y, e.elite ? "#ffb45f" : "#b6e36b", e.elite ? 20 : 11, e.elite ? 110 : 75); showCombo(); }
function arriveStation() { state.mode = "station"; state.timer = 22; state.enemies.length = 0; const before = state.trainHp; state.trainHp = Math.min(state.maxTrainHp, state.trainHp + 22); if (state.trainHp > before) showToast("列车已维修"); ui.stationScreen.hidden = false; ui.stationTitle.textContent = String(state.station).padStart(2, "0"); ui.continue.disabled = true; ui.continue.textContent = "选择模块后继续"; ui.upgrades.innerHTML = ""; upgrades.forEach((u, i) => { const card = document.createElement("button"); card.className = "upgrade-card"; card.innerHTML = `<span class="upgrade-icon">${u.icon}</span><span><h3>${u.name}</h3><p>${u.desc}</p></span><b class="upgrade-cost">${u.cost} 废料</b>`; card.addEventListener("click", () => { state.selectedUpgrade = u; ui.upgrades.querySelectorAll(".upgrade-card").forEach(x => x.classList.remove("selected")); card.classList.add("selected"); ui.continue.disabled = state.scrap < u.cost; ui.continue.textContent = state.scrap < u.cost ? "废料不足" : "装配并继续"; }); ui.upgrades.append(card); i === 0 && card.focus(); }); }
function continueRun() { if (!state.selectedUpgrade || state.scrap < state.selectedUpgrade.cost) return; state.scrap -= state.selectedUpgrade.cost; state.modules.push(state.selectedUpgrade.id); if (state.selectedUpgrade.id === "armor") { state.maxTrainHp = 125; state.trainHp = Math.min(state.maxTrainHp, state.trainHp + 25); } if (state.selectedUpgrade.id === "swarm") state.droneLevel++; state.station++; state.selectedUpgrade = null; ui.stationScreen.hidden = true; if (state.station > 3) finish(true); else { state.mode = "combat"; state.timer = 22; spawnWave(); showToast("模块在线"); updateHud(); } }
function pulse() { if (state.mode !== "combat" || state.pulseClock > 0) return; state.pulseClock = 7; state.shake = 12; state.enemies.forEach(e => { if (!e.dead && Math.hypot(e.x - state.train.x, e.y - state.train.y) < 180) { e.hp -= 3.5; burst(e.x, e.y, "#5de1df", 8, 90); if (e.hp <= 0) killEnemy(e); } }); burst(state.train.x, state.train.y, "#5de1df", 34, 170); showToast("电磁脉冲"); }
function finish(win) { state.mode = "result"; ui.result.hidden = false; $("resultBadge").textContent = win ? "◆" : "×"; $("resultEyebrow").textContent = win ? "护送完成" : "列车失守"; $("resultTitle").textContent = win ? "列车穿过了黑夜" : "铁轨被荒原吞没"; $("resultCopy").textContent = win ? "你让最后一班车抵达了安全区。" : "再多一架无人机，也许就能撑过下一站。"; $("resultKills").textContent = state.kills; $("resultStations").textContent = Math.min(state.station, 3); $("resultScrap").textContent = state.scrap; }
function updateHud() { ui.station.textContent = String(Math.min(state.station, 3)).padStart(2, "0") + " / 03"; ui.scrap.textContent = String(state.scrap).padStart(3, "0"); ui.health.textContent = Math.max(0, Math.ceil(state.trainHp)) + "%"; ui.healthFill.style.width = Math.min(100, Math.max(0, state.trainHp)) + "%"; ui.timer.textContent = Math.max(0, state.timer).toFixed(1); ui.phase.textContent = state.mode === "combat" ? "行驶中" : state.mode === "station" ? "补给站" : "待命"; ui.drone.textContent = "MK-" + ["I", "II", "III"][Math.min(2, state.droneLevel - 1)]; ui.pulseCooldown.style.height = state.pulseClock ? (state.pulseClock / 7 * 100) + "%" : "0%"; ui.pulse.classList.toggle("cooling", state.pulseClock > 0); ui.objective.textContent = state.station === 3 ? "撑过末段，抵达安全区" : "护送列车抵达下一站"; }
function showCombo() { if (state.combo < 2) return; ui.combo.textContent = "连杀 ×" + state.combo; ui.combo.classList.remove("show"); void ui.combo.offsetWidth; ui.combo.classList.add("show"); }
function showToast(text) { ui.toast.textContent = text; ui.toast.classList.remove("show"); void ui.toast.offsetWidth; ui.toast.classList.add("show"); }
function addText(text, x, y, color) { state.texts.push({ text, x, y, color, life: 1 }); }
function updateParticles(dt) { for (const p of state.particles) { p.life -= dt; p.x += p.vx * dt; p.y += p.vy * dt; p.vx *= .98; p.vy *= .98; } state.particles = state.particles.filter(p => p.life > 0); for (const t of state.texts) { t.life -= dt; t.y -= 24 * dt; } state.texts = state.texts.filter(t => t.life > 0); }
function burst(x, y, color, count, speed) { for (let i = 0; i < count; i++) { const a = Math.random() * TAU, v = speed * (.35 + Math.random() * .65); state.particles.push({ x, y, vx: Math.cos(a) * v, vy: Math.sin(a) * v, size: 2 + Math.random() * 4, life: .25 + Math.random() * .45, color }); } }

function draw() { ctx.save(); if (state.shake) ctx.translate((Math.random() - .5) * state.shake, (Math.random() - .5) * state.shake); drawBackground(); drawRails(); drawTrain(); drawEnemies(); drawShots(); drawDrone(); drawParticles(); ctx.restore(); if (state.hurtFlash) { ctx.fillStyle = `rgba(241,109,99,${state.hurtFlash * .18})`; ctx.fillRect(0, 0, W, H); } }
function drawBackground() { const g = ctx.createLinearGradient(0, 0, 0, H); g.addColorStop(0, "#102a31"); g.addColorStop(.55, "#0b1b23"); g.addColorStop(1, "#081016"); ctx.fillStyle = g; ctx.fillRect(0, 0, W, H); ctx.fillStyle = "#17353a"; for (let i = 0; i < 18; i++) { const x = (i * 83 + 31) % W, y = 110 + ((i * 47) % 260); ctx.globalAlpha = .35 + (i % 3) * .1; ctx.beginPath(); ctx.moveTo(x, y + 25); ctx.lineTo(x + 18, y - 3); ctx.lineTo(x + 35, y + 25); ctx.fill(); } ctx.globalAlpha = 1; const glow = ctx.createRadialGradient(195, 380, 20, 195, 380, 230); glow.addColorStop(0, "rgba(91,177,154,.13)"); glow.addColorStop(1, "rgba(91,177,154,0)"); ctx.fillStyle = glow; ctx.fillRect(0, 100, W, 470); }
function drawRails() { const y = 485 + Math.sin(state.railClock * 2) * 2; ctx.lineWidth = 8; ctx.strokeStyle = "#5d473a"; ctx.beginPath(); ctx.moveTo(136, 80); ctx.lineTo(170, y + 100); ctx.stroke(); ctx.beginPath(); ctx.moveTo(254, 80); ctx.lineTo(220, y + 100); ctx.stroke(); ctx.lineWidth = 3; ctx.strokeStyle = "#c48658"; ctx.beginPath(); ctx.moveTo(142, 80); ctx.lineTo(175, y + 100); ctx.stroke(); ctx.beginPath(); ctx.moveTo(248, 80); ctx.lineTo(215, y + 100); ctx.stroke(); for (let i = 0; i < 12; i++) { const t = (i / 12 + state.railClock * .12) % 1, yy = 120 + t * 450, spread = 20 + t * 110; ctx.strokeStyle = i % 2 ? "#6c5241" : "#8b654d"; ctx.lineWidth = 4; ctx.beginPath(); ctx.moveTo(195 - spread, yy); ctx.lineTo(195 + spread, yy); ctx.stroke(); } }
function drawTrain() { const x = state.train.x, y = state.train.y; ctx.save(); ctx.translate(x, y); ctx.fillStyle = "rgba(0,0,0,.35)"; ctx.fillRect(-70, 33, 140, 15); ctx.fillStyle = "#341f25"; ctx.fillRect(-57, -38, 114, 73); ctx.fillStyle = "#a54c3d"; ctx.fillRect(-51, -35, 102, 65); ctx.fillStyle = "#d16b47"; ctx.fillRect(-42, -29, 43, 29); ctx.fillStyle = "#edbd76"; ctx.fillRect(-34, -23, 26, 17); ctx.fillStyle = "#723638"; ctx.fillRect(9, -29, 35, 51); ctx.fillStyle = "#2c2024"; ctx.fillRect(17, -23, 20, 23); ctx.fillStyle = "#e4a05d"; ctx.fillRect(-60, -10, 9, 21); ctx.fillStyle = "#17262a"; ctx.fillRect(-43, 22, 20, 11); ctx.fillRect(23, 22, 20, 11); ctx.fillStyle = "#f1d6a2"; ctx.fillRect(-7, -42, 14, 8); ctx.fillStyle = "#5de1df"; ctx.shadowColor = "#5de1df"; ctx.shadowBlur = 12; ctx.fillRect(-5, -13, 10, 10); ctx.shadowBlur = 0; ctx.restore(); }
function drawEnemies() { for (const e of state.enemies) { if (e.dead || e.delay > 0) continue; ctx.save(); ctx.translate(e.x, e.y); const s = 1 + e.hit * .16; ctx.scale(s, s); ctx.fillStyle = "#18221f"; ctx.beginPath(); ctx.arc(0, 0, e.r + 4, 0, TAU); ctx.fill(); ctx.fillStyle = e.elite ? "#df754d" : (e.hue > .5 ? "#9acb61" : "#65a98d"); ctx.beginPath(); ctx.arc(0, 0, e.r, 0, TAU); ctx.fill(); ctx.fillStyle = "#152025"; ctx.fillRect(-e.r * .65, -3, e.r * 1.3, 6); ctx.fillStyle = "#e9f3d2"; ctx.fillRect(-e.r * .48, -e.r * .35, 4, 4); ctx.fillRect(e.r * .2, -e.r * .35, 4, 4); if (e.elite) { ctx.strokeStyle = "#ffb45f"; ctx.lineWidth = 2; ctx.beginPath(); ctx.arc(0, 0, e.r + 5, 0, TAU); ctx.stroke(); } ctx.restore(); if (e.hp < e.maxHp) { ctx.fillStyle = "#203238"; ctx.fillRect(e.x - 18, e.y + e.r + 7, 36, 4); ctx.fillStyle = e.elite ? "#ffb45f" : "#b6e36b"; ctx.fillRect(e.x - 17, e.y + e.r + 8, 34 * Math.max(0, e.hp / e.maxHp), 2); } } }
function drawShots() { for (const s of state.shots) { ctx.strokeStyle = s.color; ctx.lineWidth = 3; ctx.shadowColor = s.color; ctx.shadowBlur = 9; ctx.beginPath(); ctx.moveTo(s.x, s.y); ctx.lineTo(s.x - s.vx * .035, s.y - s.vy * .035); ctx.stroke(); ctx.shadowBlur = 0; } }
function drawDrone() { const x = state.drone.x, y = state.drone.y; ctx.save(); ctx.translate(x, y); ctx.rotate(Math.sin(performance.now() / 240) * .08); ctx.strokeStyle = "rgba(93,225,223,.28)"; ctx.lineWidth = 2; ctx.beginPath(); ctx.arc(0, 0, 27 + Math.sin(performance.now() / 180) * 3, 0, TAU); ctx.stroke(); ctx.fillStyle = "#152d32"; ctx.strokeStyle = "#5de1df"; ctx.lineWidth = 3; ctx.beginPath(); ctx.ellipse(0, 0, 23, 11, 0, 0, TAU); ctx.fill(); ctx.stroke(); ctx.fillStyle = "#ffb45f"; ctx.fillRect(-5, -4, 10, 8); ctx.fillStyle = "#5de1df"; ctx.fillRect(-19, -16, 11, 5); ctx.fillRect(8, -16, 11, 5); ctx.restore(); }
function drawParticles() { for (const p of state.particles) { ctx.globalAlpha = Math.min(1, p.life * 2); ctx.fillStyle = p.color; ctx.fillRect(p.x, p.y, p.size, p.size); } ctx.globalAlpha = 1; ctx.font = "bold 12px ui-monospace,monospace"; ctx.textAlign = "center"; for (const t of state.texts) { ctx.globalAlpha = Math.min(1, t.life * 2); ctx.fillStyle = t.color; ctx.fillText(t.text, t.x, t.y); } ctx.globalAlpha = 1; }

function setPointer(e) { const r = canvas.getBoundingClientRect(); state.drone.tx = Math.max(46, Math.min(W - 46, (e.clientX - r.left) / r.width * W)); state.drone.ty = Math.max(120, Math.min(H - 110, (e.clientY - r.top) / r.height * H)); ui.hint.style.opacity = 0; }
canvas.addEventListener("pointerdown", e => { canvas.setPointerCapture(e.pointerId); setPointer(e); }); canvas.addEventListener("pointermove", e => { if (e.buttons || e.pointerType === "touch") setPointer(e); });
ui.pulse.addEventListener("click", pulse); $("startButton").addEventListener("click", resetRun); $("restartButton").addEventListener("click", resetRun); ui.continue.addEventListener("click", continueRun);
window.addEventListener("keydown", e => { if (e.code === "Space") { e.preventDefault(); pulse(); } });
let last = performance.now(); function frame(now) { const dt = Math.min(.033, (now - last) / 1000); last = now; update(dt); draw(); requestAnimationFrame(frame); } updateHud(); requestAnimationFrame(frame);
