"use strict";
const canvas=document.getElementById("gameCanvas"),ctx=canvas.getContext("2d"),W=canvas.width,H=canvas.height,TAU=Math.PI*2,$=id=>document.getElementById(id),motion=window.EndlessRailsMotion||{FORWARD:{x:.5,y:-Math.sqrt(3)/2},spawnPoint(side,width,height,margin,random=Math.random){const along=random()*(side==="top"||side==="bottom"?width+margin*2:height+margin*2)-margin;if(side==="top")return{x:along,y:-margin};if(side==="right")return{x:width+margin,y:along};if(side==="bottom")return{x:along,y:height+margin};return{x:-margin,y:along}},stepChaser(entity,dt,center,driftSpeed){const dx=center.x-entity.x,dy=center.y-entity.y,d=Math.hypot(dx,dy)||1;return{x:entity.x-motion.FORWARD.x*driftSpeed*dt+dx/d*entity.speed*dt,y:entity.y-motion.FORWARD.y*driftSpeed*dt+dy/d*entity.speed*dt}}};
const WORLD_SPEED=88;
const balance=window.EndlessRailsBalance||{START_TRAIN_LENGTH:3,REGULAR_ENEMY_HP_BASE:1.3,REGULAR_ENEMY_HP_STEP:.16,ELITE_ENEMY_HP_BASE:4,ELITE_ENEMY_HP_STEP:.4,REGULAR_ENEMY_SPEED_BASE:88,REGULAR_ENEMY_SPEED_JITTER:16,REGULAR_ENEMY_SPEED_STEP:4,ELITE_ENEMY_SPEED_BASE:108,ELITE_ENEMY_SPEED_STEP:4,RAIL_HALF_LENGTH:1100,RAIL_WIDTH:8,RAIL_EDGE_WIDTH:2.5,SLEEPER_WIDTH:4,CAR_LENGTH:50,CAR_HEIGHT:34,CAR_SPACING:58,SPAWN_BATCH_SIZE:2,ENEMY_CAP:18,BOSS_ENEMY_CAP:22,SPAWN_INTERVAL_BASE:.42,SPAWN_INTERVAL_STEP:.025,DRONE_BASE_DAMAGE:1.55,HIT_PARTICLE_COUNT:8,initialWaveCount:station=>station===5?12:7+station,enemyCap:station=>station===5?22:18,spawnInterval:station=>Math.max(.24,.42-station*.025)};
const ui={station:$("stationValue"),scrap:$("scrapValue"),health:$("healthText"),healthFill:$("healthFill"),timer:$("timerValue"),phase:$("phaseLabel"),drone:$("droneLevel"),pulse:$("pulseButton"),pulseCooldown:$("pulseCooldown"),objective:$("objectiveText"),combo:$("comboText"),toast:$("toast"),hint:$("touchHint"),start:$("startScreen"),stationScreen:$("stationScreen"),stationTitle:$("stationTitle"),upgrades:$("upgradeList"),continue:$("continueButton"),result:$("resultScreen"),bossWrap:$("bossWrap"),bossText:$("bossText"),bossFill:$("bossFill"),trainLength:$("trainLengthLabel"),miniTrain:$("miniTrain")};
const upgradePool=[
 {id:"rapid",type:"drone",icon:"ϟ",name:"脉冲机枪",desc:"射速提升 28%。",cost:28},{id:"missile",type:"drone",icon:"➤",name:"追踪导弹",desc:"每轮发射一枚高伤导弹。",cost:38},{id:"scatter",type:"drone",icon:"✣",name:"裂片散射",desc:"每次射击额外释放两枚碎弹。",cost:44},{id:"tesla",type:"drone",icon:"∿",name:"电弧线圈",desc:"命中后跳电附近目标。",cost:52},{id:"wingman",type:"drone",icon:"◇",name:"伴飞无人机",desc:"增加一架伴飞机，火力 +45%。",cost:64},{id:"overclock",type:"drone",icon:"◎",name:"过载核心",desc:"脉冲冷却时间缩短 30%。",cost:58},
 {id:"armor",type:"train",icon:"⬢",name:"装甲铆接",desc:"最大完整度 +25，撞击伤害降低。",cost:42},{id:"railgun",type:"train",icon:"⌁",name:"车头磁轨炮",desc:"列车向前方周期性发射穿透弹。",cost:46},{id:"cargo",type:"train",icon:"▣",name:"货运舱",desc:"车厢 +1，击破废料收益 +30%。",cost:48},{id:"repair",type:"train",icon:"+",name:"维修车",desc:"每到站额外修复 18 点完整度。",cost:50},{id:"shield",type:"train",icon:"◈",name:"偏转护盾",desc:"每轮抵挡第一次撞击。",cost:55},{id:"magnet",type:"train",icon:"⊕",name:"废料磁吸",desc:"废料收益 +50%，并吸引远处掉落。",cost:60}];
const state={mode:"menu",station:1,timer:20,maxTrainHp:100,trainHp:100,scrap:0,kills:0,combo:0,bestCombo:0,score:0,droneLevel:1,trainLength:balance.START_TRAIN_LENGTH,fireClock:0,missileClock:0,spawnClock:.2,pulseClock:0,railClock:0,hurtFlash:0,shake:0,drone:{x:240,y:300,tx:240,ty:300},train:{x:W/2,y:H/2},enemies:[],shots:[],particles:[],texts:[],selectedUpgrade:null,modules:{},boss:null,shieldReady:false};
const level=id=>state.modules[id]||0;
function resetRun(){Object.assign(state,{mode:"combat",station:1,timer:20,maxTrainHp:100,trainHp:100,scrap:0,kills:0,combo:0,bestCombo:0,score:0,droneLevel:1,trainLength:balance.START_TRAIN_LENGTH,fireClock:0,missileClock:0,spawnClock:.2,pulseClock:0,railClock:0,hurtFlash:0,shake:0,enemies:[],shots:[],particles:[],texts:[],selectedUpgrade:null,modules:{},boss:null,shieldReady:false});state.train.x=W/2;state.train.y=H/2;ui.start.hidden=true;ui.stationScreen.hidden=true;ui.result.hidden=true;ui.hint.style.opacity=.8;spawnWave();updateHud()}
function spawnWave(){const count=balance.initialWaveCount(state.station);for(let i=0;i<count;i++)spawnEnemy(i*.14);if(state.station===5){state.boss={hp:62,maxHp:62,x:W/2+105,y:H/2-180,r:34,speed:34,hit:0,summon:3.2,dead:false};ui.bossWrap.hidden=false}else{state.boss=null;ui.bossWrap.hidden=true}}
function spawnEnemy(delay=0){const sides=["top","right","bottom","left"],side=sides[Math.floor(Math.random()*sides.length)],point=motion.spawnPoint(side,W,H,44),elite=Math.random()<.07*state.station,hp=elite?balance.ELITE_ENEMY_HP_BASE+state.station*balance.ELITE_ENEMY_HP_STEP:balance.REGULAR_ENEMY_HP_BASE+state.station*balance.REGULAR_ENEMY_HP_STEP;state.enemies.push({x:point.x,y:point.y,r:elite?19:13+Math.random()*3,hp,maxHp:hp,speed:elite?balance.ELITE_ENEMY_SPEED_BASE+state.station*balance.ELITE_ENEMY_SPEED_STEP:balance.REGULAR_ENEMY_SPEED_BASE+Math.random()*balance.REGULAR_ENEMY_SPEED_JITTER+state.station*balance.REGULAR_ENEMY_SPEED_STEP,hue:Math.random(),elite,side,delay,hit:0,dead:false})}
function update(dt){if(state.mode!=="combat")return;state.timer-=dt;state.fireClock-=dt;state.missileClock-=dt;state.spawnClock-=dt;state.pulseClock=Math.max(0,state.pulseClock-dt);state.railClock+=dt;state.hurtFlash=Math.max(0,state.hurtFlash-dt);state.shake=Math.max(0,state.shake-dt*20);state.drone.x+=(state.drone.tx-state.drone.x)*Math.min(1,dt*10);state.drone.y+=(state.drone.ty-state.drone.y)*Math.min(1,dt*10);const cap=balance.enemyCap(state.station);if(state.spawnClock<=0&&state.enemies.filter(e=>!e.dead).length<cap){for(let i=0;i<balance.SPAWN_BATCH_SIZE&&state.enemies.filter(e=>!e.dead).length<cap;i++)spawnEnemy(i*.08);state.spawnClock=balance.spawnInterval(state.station)}for(const e of state.enemies){if(e.dead)continue;if(e.delay>0){e.delay-=dt;continue}const next=motion.stepChaser(e,dt,state.train,WORLD_SPEED);e.x=next.x;e.y=next.y;e.hit=Math.max(0,e.hit-dt*5);if(Math.hypot(state.train.x-e.x,state.train.y-e.y)<46)collideTrain(e)}if(state.boss&&!state.boss.dead){const b=state.boss;b.hit=Math.max(0,b.hit-dt*4);b.summon-=dt;const next=motion.stepChaser(b,dt,state.train,WORLD_SPEED*.45);b.x=next.x;b.y=next.y;if(b.summon<=0){for(let i=0;i<3;i++)spawnEnemy(i*.15);b.summon=5;showToast("掘行者召唤了护卫")}}if(state.fireClock<=0){fireDrone();state.fireClock=Math.max(.14,.4-level("rapid")*.07-state.droneLevel*.025)}if(level("missile")&&state.missileClock<=0){fireMissile();state.missileClock=Math.max(2.3,5-level("missile")*.7)}if(level("railgun")&&state.railClock>1.2){fireRailgun();state.railClock=0}updateShots(dt);updateParticles(dt);if(state.trainHp<=0)finish(false);else if(state.station===5&&state.boss?.dead)finish(true);else if(state.timer<=0&&state.station<5)arriveStation();else if(state.timer<=0&&state.station===5){state.timer=28;showToast("继续压制掘行者")};updateHud()}
function collideTrain(e){e.dead=true;if(state.shieldReady){state.shieldReady=false;burst(e.x,e.y,"#7ce9e6",14,80);showToast("护盾挡下撞击");return}const damage=(e.elite?11:6)*(1-Math.min(.36,level("armor")*.12));state.trainHp=Math.max(0,state.trainHp-damage);state.hurtFlash=.3;state.shake=5;burst(e.x,e.y,"#f16d63",9,60);addText("-"+Math.ceil(damage),state.train.x,state.train.y-40,"#f16d63")}
function fireDrone(){const targets=state.enemies.filter(e=>!e.dead&&e.delay<=0);if(state.boss&&!state.boss.dead)targets.push(state.boss);if(!targets.length)return;targets.sort((a,b)=>Math.hypot(a.x-state.drone.x,a.y-state.drone.y)-Math.hypot(b.x-state.drone.x,b.y-state.drone.y));const t=targets[0],a=Math.atan2(t.y-state.drone.y,t.x-state.drone.x),count=1+level("scatter")*2;for(let i=0;i<count;i++){const spread=count===1?0:(i-(count-1)/2)*.12;state.shots.push({x:state.drone.x,y:state.drone.y,vx:Math.cos(a+spread)*410,vy:Math.sin(a+spread)*410,life:1,damage:balance.DRONE_BASE_DAMAGE+level("rapid")*.12,color:state.droneLevel>1?"#ffb45f":"#5de1df"})}burst(state.drone.x,state.drone.y,"#5de1df",2,25)}
function fireMissile(){const t=state.enemies.find(e=>!e.dead&&e.delay<=0)||state.boss;if(!t)return;const a=Math.atan2(t.y-state.drone.y,t.x-state.drone.x);state.shots.push({x:state.drone.x,y:state.drone.y,vx:Math.cos(a)*250,vy:Math.sin(a)*250,life:2.1,damage:3+level("missile"),missile:true,color:"#ff8b56"});burst(state.drone.x,state.drone.y,"#ffb45f",7,60)}
function fireRailgun(){const t=state.enemies.find(e=>!e.dead&&e.delay<=0)||state.boss;if(!t)return;const a=Math.atan2(t.y-(state.train.y-28),t.x-state.train.x);state.shots.push({x:state.train.x,y:state.train.y-28,vx:Math.cos(a)*500,vy:Math.sin(a)*500,life:1.2,damage:2.6,railgun:true,color:"#ffb45f"});burst(state.train.x,state.train.y-28,"#ffb45f",7,50)}
function updateShots(dt){for(let i=state.shots.length-1;i>=0;i--){const s=state.shots[i];s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;let hit=false;const targets=[...state.enemies.filter(e=>!e.dead&&e.delay<=0),...(state.boss&&!state.boss.dead?[state.boss]:[])];for(const e of targets){if(s.hitIds?.includes(e))continue;if(Math.hypot(e.x-s.x,e.y-s.y)<e.r+6){e.hp-=s.damage;e.hit=1;s.hitIds||=[];s.hitIds.push(e);burst(s.x,s.y,e===state.boss?"#ffb45f":"#b6e36b",balance.HIT_PARTICLE_COUNT,52);if(e.hp<=0)e===state.boss?killBoss():killEnemy(e);if(!s.railgun&&!s.missile)hit=true;if(hit)break}}if(hit||s.life<=0)state.shots.splice(i,1)}}
function killEnemy(e){e.dead=true;state.kills++;state.combo++;state.bestCombo=Math.max(state.bestCombo,state.combo);const gain=Math.ceil((e.elite?14:6)*(1+level("cargo")*.3+level("magnet")*.5));state.scrap+=gain;state.score+=(e.elite?130:50)*Math.max(1,state.combo);state.shake=e.elite?7:3;addText("+"+gain,e.x,e.y-15,"#ffb45f");burst(e.x,e.y,e.elite?"#ffb45f":"#b6e36b",e.elite?26:16,e.elite?125:90);showCombo()}
function killBoss(){if(!state.boss||state.boss.dead)return;state.boss.dead=true;state.score+=1200;state.scrap+=80;state.shake=15;burst(state.boss.x,state.boss.y,"#ffb45f",60,190);showToast("掘行者核心崩解")}
function arriveStation(){state.mode="station";state.timer=20;state.enemies.length=0;state.boss=null;ui.bossWrap.hidden=true;const repair=22+level("repair")*18,before=state.trainHp;state.trainHp=Math.min(state.maxTrainHp,state.trainHp+repair);state.shieldReady=!!level("shield");if(state.trainHp>before)showToast("列车已维修");ui.stationScreen.hidden=false;ui.stationTitle.textContent=String(state.station).padStart(2,"0");ui.continue.disabled=true;ui.continue.textContent="选择模块后继续";ui.upgrades.innerHTML="";renderUpgradeChoices();renderTrainPreview()}
function renderUpgradeChoices(){const pool=[...upgradePool].sort(()=>Math.random()-.5),picks=[],drone=pool.find(u=>u.type==="drone"),train=pool.find(u=>u.type==="train");picks.push(drone,train);for(const u of pool)if(!picks.includes(u)&&picks.length<5)picks.push(u);picks.forEach(u=>{const card=document.createElement("button");card.className="upgrade-card";card.dataset.type=u.type;const current=level(u.id);card.innerHTML=`<span class="upgrade-icon">${u.icon}</span><span><h3>${u.name} <small>Lv.${current+1}</small></h3><p>${u.type==="drone"?"飞机 · ":"列车 · "}${u.desc}</p></span><b class="upgrade-cost">${u.cost} 废料</b>`;card.addEventListener("click",()=>{state.selectedUpgrade=u;ui.upgrades.querySelectorAll(".upgrade-card").forEach(x=>x.classList.remove("selected"));card.classList.add("selected");ui.continue.disabled=state.scrap<u.cost;ui.continue.textContent=state.scrap<u.cost?"废料不足":"装配并继续"});ui.upgrades.append(card)})}
function renderTrainPreview(){ui.trainLength.textContent=state.trainLength+" 节车厢";ui.miniTrain.innerHTML="";for(let i=0;i<Math.min(7,state.trainLength+1);i++){const car=document.createElement("i");car.className="mini-car"+(i===0?" mini-car--cab":"");car.textContent=i===0?"◆":i%2?"▦":"▤";ui.miniTrain.append(car)}}
function continueRun(){const u=state.selectedUpgrade;if(!u||state.scrap<u.cost)return;state.scrap-=u.cost;state.modules[u.id]=level(u.id)+1;if(u.id==="armor"){state.maxTrainHp+=25;state.trainHp=Math.min(state.maxTrainHp,state.trainHp+25)}if(u.id==="cargo")state.trainLength++;if(u.id==="wingman")state.droneLevel++;state.station++;state.selectedUpgrade=null;ui.stationScreen.hidden=true;if(state.station>5)finish(true);else{state.mode="combat";state.timer=state.station===5?28:20;spawnWave();showToast("模块在线");updateHud()}}
function pulse(){if(state.mode!=="combat"||state.pulseClock>0)return;state.pulseClock=Math.max(3.8,7-level("overclock")*1.4);state.shake=12;state.enemies.forEach(e=>{if(!e.dead&&Math.hypot(e.x-state.train.x,e.y-state.train.y)<190){e.hp-=4.5;burst(e.x,e.y,"#5de1df",10,100);if(e.hp<=0)killEnemy(e)}});if(state.boss&&Math.hypot(state.boss.x-state.train.x,state.boss.y-state.train.y)<220){state.boss.hp-=8;state.boss.hit=1;if(state.boss.hp<=0)killBoss()}burst(state.train.x,state.train.y,"#5de1df",34,170);showToast("电磁脉冲")}
function finish(win){state.mode="result";ui.result.hidden=false;$("resultBadge").textContent=win?"◆":"×";$("resultEyebrow").textContent=win?"护送完成":"列车失守";$("resultTitle").textContent=win?"列车穿过了黑夜":"铁轨被荒原吞没";$("resultCopy").textContent=win?"你让最后一班车抵达了安全区。":"再多一架无人机，也许就能撑过下一站。";$("resultKills").textContent=state.kills;$("resultStations").textContent=Math.min(state.station,5);$("resultScrap").textContent=state.scrap}
function updateHud(){ui.station.textContent=String(Math.min(state.station,5)).padStart(2,"0")+" / 05";ui.scrap.textContent=String(state.scrap).padStart(3,"0");ui.health.textContent=Math.max(0,Math.ceil(state.trainHp))+"%";ui.healthFill.style.width=Math.min(100,Math.max(0,state.trainHp/state.maxTrainHp*100))+"%";ui.timer.textContent=Math.max(0,state.timer).toFixed(1);ui.phase.textContent=state.mode==="combat"?"行驶中":state.mode==="station"?"补给站":"待命";ui.drone.textContent="MK-"+["I","II","III"][Math.min(2,state.droneLevel-1)];ui.pulseCooldown.style.height=state.pulseClock?state.pulseClock/7*100+"%":"0%";ui.pulse.classList.toggle("cooling",state.pulseClock>0);ui.objective.textContent=state.station===5?"击破荒原掘行者，护送列车":"护送列车抵达下一站";if(state.boss){ui.bossText.textContent=Math.max(0,Math.ceil(state.boss.hp))+"%";ui.bossFill.style.width=Math.max(0,state.boss.hp/state.boss.maxHp*100)+"%"}}
function showCombo(){if(state.combo<2)return;ui.combo.textContent="连杀 ×"+state.combo;ui.combo.classList.remove("show");void ui.combo.offsetWidth;ui.combo.classList.add("show")}
function showToast(text){ui.toast.textContent=text;ui.toast.classList.remove("show");void ui.toast.offsetWidth;ui.toast.classList.add("show")}
function addText(text,x,y,color){state.texts.push({text,x,y,color,life:1})}function updateParticles(dt){for(const p of state.particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.98;p.vy*=.98}state.particles=state.particles.filter(p=>p.life>0);for(const t of state.texts){t.life-=dt;t.y-=24*dt}state.texts=state.texts.filter(t=>t.life>0)}function burst(x,y,color,count,speed){for(let i=0;i<count;i++){const a=Math.random()*TAU,v=speed*(.35+Math.random()*.65);state.particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,size:2+Math.random()*4,life:.25+Math.random()*.45,color})}}
function draw(){ctx.save();if(state.shake)ctx.translate((Math.random()-.5)*state.shake,(Math.random()-.5)*state.shake);drawBackground();drawRails();drawTrain();drawEnemies();drawBoss();drawShots();drawDrone();drawParticles();ctx.restore();if(state.hurtFlash){ctx.fillStyle=`rgba(241,109,99,${state.hurtFlash*.18})`;ctx.fillRect(0,0,W,H)}}
function drawEnemies(){for(const e of state.enemies){if(e.dead||e.delay>0)continue;ctx.save();ctx.translate(e.x,e.y);const s=1+e.hit*.16;ctx.scale(s,s);ctx.fillStyle="#18221f";ctx.beginPath();ctx.arc(0,0,e.r+4,0,TAU);ctx.fill();ctx.fillStyle=e.elite?"#df754d":e.hue>.5?"#9acb61":"#65a98d";ctx.beginPath();ctx.arc(0,0,e.r,0,TAU);ctx.fill();ctx.fillStyle="#152025";ctx.fillRect(-e.r*.65,-3,e.r*1.3,6);ctx.fillStyle="#e9f3d2";ctx.fillRect(-e.r*.48,-e.r*.35,4,4);ctx.fillRect(e.r*.2,-e.r*.35,4,4);if(e.elite){ctx.strokeStyle="#ffb45f";ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,e.r+5,0,TAU);ctx.stroke()}ctx.restore();if(e.hp<e.maxHp){ctx.fillStyle="#203238";ctx.fillRect(e.x-18,e.y+e.r+7,36,4);ctx.fillStyle=e.elite?"#ffb45f":"#b6e36b";ctx.fillRect(e.x-17,e.y+e.r+8,34*Math.max(0,e.hp/e.maxHp),2)}}}
function drawBoss(){const b=state.boss;if(!b||b.dead)return;ctx.save();ctx.translate(b.x,b.y);ctx.fillStyle="#251c24";ctx.strokeStyle="#ffb45f";ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,b.r+8,0,TAU);ctx.fill();ctx.stroke();ctx.fillStyle="#9b463b";ctx.fillRect(-b.r,-b.r*.7,b.r*2,b.r*1.4);ctx.fillStyle=b.hit?"#fff0a2":"#5de1df";ctx.fillRect(-13,-13,26,26);ctx.fillStyle="#f5dfb1";ctx.fillRect(-27,-22,8,8);ctx.fillRect(19,-22,8,8);ctx.restore()}
function drawShots(){for(const s of state.shots){ctx.strokeStyle=s.color;ctx.lineWidth=s.missile?6:4;ctx.shadowColor=s.color;ctx.shadowBlur=s.missile?15:11;ctx.beginPath();ctx.moveTo(s.x,s.y);ctx.lineTo(s.x-s.vx*.035,s.y-s.vy*.035);ctx.stroke();ctx.shadowBlur=0}}
function drawDrone(){const x=state.drone.x,y=state.drone.y;ctx.save();ctx.translate(x,y);ctx.rotate(Math.sin(performance.now()/240)*.08);ctx.strokeStyle="rgba(93,225,223,.28)";ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,27+Math.sin(performance.now()/180)*3,0,TAU);ctx.stroke();ctx.fillStyle="#152d32";ctx.strokeStyle="#5de1df";ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(0,0,23,11,0,0,TAU);ctx.fill();ctx.stroke();ctx.fillStyle="#ffb45f";ctx.fillRect(-5,-4,10,8);ctx.fillStyle="#5de1df";ctx.fillRect(-19,-16,11,5);ctx.fillRect(8,-16,11,5);if(state.droneLevel>1){ctx.strokeStyle="#ffb45f";ctx.beginPath();ctx.arc(0,0,31,0,TAU);ctx.stroke()}ctx.restore()}
function drawParticles(){for(const p of state.particles){ctx.globalAlpha=Math.min(1,p.life*2);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.size,p.size)}ctx.globalAlpha=1;ctx.font="bold 12px ui-monospace,monospace";ctx.textAlign="center";for(const t of state.texts){ctx.globalAlpha=Math.min(1,t.life*2);ctx.fillStyle=t.color;ctx.fillText(t.text,t.x,t.y)}ctx.globalAlpha=1}

function drawBackground(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,"#102a31");g.addColorStop(.55,"#0b1b23");g.addColorStop(1,"#081016");ctx.fillStyle=g;ctx.fillRect(0,0,W,H);const drift=(state.railClock*WORLD_SPEED)%160,forward=motion.FORWARD;for(let i=-3;i<9;i++){const x=((i*77-drift*forward.x)%460+460)%460,y=90+i*88-drift*forward.y;ctx.fillStyle=i%2?"#173b3c":"#1a3034";ctx.globalAlpha=.42;ctx.beginPath();ctx.moveTo(x,y+28);ctx.lineTo(x+18,y-6);ctx.lineTo(x+36,y+28);ctx.fill()}ctx.globalAlpha=1;for(let i=0;i<12;i++){const t=(i*.17+(state.railClock*.32))%1,x=28+t*390-drift*forward.x,y=112+t*380-drift*forward.y;ctx.strokeStyle=i%2?"rgba(125,180,157,.12)":"rgba(255,180,95,.14)";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-42,y+48);ctx.stroke()}}
function drawRails(){const {x:fx,y:fy}=motion.FORWARD,nx=-fy,ny=fx,spacing=42,railLength=balance.RAIL_HALF_LENGTH,scroll=(state.railClock*WORLD_SPEED*2.6)%spacing;ctx.lineCap="round";for(const side of[-1,1]){const ox=nx*side*15,oy=ny*side*15;ctx.strokeStyle="#3e3433";ctx.lineWidth=balance.RAIL_WIDTH;ctx.beginPath();ctx.moveTo(state.train.x+ox-fx*railLength,state.train.y+oy-fy*railLength);ctx.lineTo(state.train.x+ox+fx*railLength,state.train.y+oy+fy*railLength);ctx.stroke();ctx.strokeStyle="#c08359";ctx.lineWidth=balance.RAIL_EDGE_WIDTH;ctx.beginPath();ctx.moveTo(state.train.x+ox-fx*railLength,state.train.y+oy-fy*railLength);ctx.lineTo(state.train.x+ox+fx*railLength,state.train.y+oy+fy*railLength);ctx.stroke()}for(let t=-railLength-scroll;t<railLength;t+=spacing){const cx=state.train.x+fx*t,cy=state.train.y+fy*t;ctx.strokeStyle=t<0?"#77503f":"#a36b4e";ctx.lineWidth=balance.SLEEPER_WIDTH;ctx.beginPath();ctx.moveTo(cx-nx*31,cy-ny*31);ctx.lineTo(cx+nx*31,cy+ny*31);ctx.stroke()}ctx.lineCap="butt"}
function carPosition(i){const {x:fx,y:fy}=motion.FORWARD;return{x:state.train.x-fx*i*balance.CAR_SPACING,y:state.train.y-fy*i*balance.CAR_SPACING}}
function drawTrain(){const angle=Math.atan2(motion.FORWARD.y,motion.FORWARD.x),half=balance.CAR_LENGTH/2,body=balance.CAR_HEIGHT;for(let i=state.trainLength-1;i>=0;i--){const p=carPosition(i);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(angle);if(i>0){ctx.fillStyle="#2b2425";ctx.fillRect(half,-3,balance.CAR_SPACING-balance.CAR_LENGTH,6)}ctx.fillStyle="rgba(0,0,0,.35)";ctx.fillRect(-half+2,body/2-1,balance.CAR_LENGTH-4,9);ctx.fillStyle=i===0?"#c65c40":i%2?"#81453d":"#9d4f3e";ctx.strokeStyle="#351f25";ctx.lineWidth=5;ctx.fillRect(-half,-body/2,balance.CAR_LENGTH,body);ctx.strokeRect(-half,-body/2,balance.CAR_LENGTH,body);ctx.fillStyle=i===0?"#f0b76c":"#d98554";ctx.fillRect(-half+9,-body/2+7,12,10);ctx.fillRect(-half+25,-body/2+7,12,10);ctx.fillStyle="#1a282c";ctx.fillRect(-half+4,body/2-4,11,7);ctx.fillRect(half-15,body/2-4,11,7);if(i===0){ctx.fillStyle="#5de1df";ctx.shadowColor="#5de1df";ctx.shadowBlur=12;ctx.fillRect(-4,-5,9,9);ctx.shadowBlur=0;ctx.fillStyle="#2e2526";ctx.beginPath();ctx.moveTo(half,-body/2+4);ctx.lineTo(half+8,0);ctx.lineTo(half,body/2-4);ctx.fill()}ctx.restore()}}
function setPointer(e){const r=canvas.getBoundingClientRect();state.drone.tx=Math.max(46,Math.min(W-46,(e.clientX-r.left)/r.width*W));state.drone.ty=Math.max(120,Math.min(H-110,(e.clientY-r.top)/r.height*H));ui.hint.style.opacity=0}canvas.addEventListener("pointerdown",e=>{canvas.setPointerCapture(e.pointerId);setPointer(e)});canvas.addEventListener("pointermove",e=>{if(e.buttons||e.pointerType==="touch")setPointer(e)});ui.pulse.addEventListener("click",pulse);$("startButton").addEventListener("click",resetRun);$("restartButton").addEventListener("click",resetRun);ui.continue.addEventListener("click",continueRun);window.addEventListener("keydown",e=>{if(e.code==="Space"){e.preventDefault();pulse()}});let last=performance.now();function frame(now){const dt=Math.min(.033,(now-last)/1000);last=now;update(dt);draw();requestAnimationFrame(frame)}updateHud();requestAnimationFrame(frame);
