"use strict";
const assert=require("node:assert/strict");
const createGame=require("./test-harness.cjs");
const calls=[];
const context=new Proxy({drawImage(...args){calls.push(args);},createRadialGradient(){return {addColorStop(){}};}},{get:(target,key)=>target[key]||(()=>{})});
const game=createGame({context});
game.sandbox.vfxImage={naturalWidth:1254,naturalHeight:1254};
game.run("gameArt.vfx=vfxImage; state.visualTime=1; state.mode='combat';");
game.run("paintWeaponVfx(2,1.5,90,100,120,.7)");
assert.equal(calls.length,2,"loop frames are crossfaded");
assert.deepEqual(calls.map(c=>c.slice(1,5)),[[313.5,627,313.5,313.5],[627,627,313.5,313.5]]);
calls.length=0;
game.run("state.shots=[{x:1,y:150,vx:-270,vy:0,life:4,bounce:true,bounces:3,damage:1,owner:'ricochet'}];updateShots(.016);drawShots();drawWeaponEffects();");
assert.ok(game.run("state.weaponFx.some(f=>f.kind==='ricochetBurst')"));
assert.ok(calls.some(c=>c[2]===313.5),"reflection draws the violet impact row");
game.run("for(let i=0;i<50;i++)ricochetBurst(100,100,30)");
assert.equal(game.run("state.weaponFx.filter(f=>f.kind==='ricochetBurst').length"),24,"horde impact sprites stay bounded");
calls.length=0;
game.run("state.zones=[{x:100,y:100,r:55,flight:0,life:3.7,duration:3.8,phase:0}];drawZones();");
assert.ok(calls.some(c=>c[2]===627),"fire uses the generated ground animation");
assert.ok(calls.some(c=>c[2]===940.5),"landing uses the generated explosion animation");
game.run("advanceWorld(10)");
assert.notEqual(game.run("state.zones[0].y"),100,"fire sprites remain attached to the scrolling ground");
assert.equal(game.run("effects.droneLabel('ricochet')"),"回响 · 跳弹");
assert.equal(game.run("effects.droneLabel('incendiary')"),"烛龙 · 燃烧");
assert.equal(game.run("effects.droneLabel('command')"),"北辰 · 指挥");
assert.ok(game.run("experiencePool.every(u=>u.name===effects.droneLabel(u.id))"));
game.run("renderPause()");
assert.match(game.elements.inspectSelect.innerHTML,/回响 · 跳弹/);
assert.match(game.elements.inspectSelect.innerHTML,/北辰 · 指挥/);
console.log("Generated VFX frames, ricochet bursts, ground attachment, budget and fleet names passed.");
