"""Pack approved originals; Pillow only resizes/crops/packs, never redraws art."""
from pathlib import Path
from PIL import Image
import json
ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT/'endless-rails/assets'
SOURCE = ASSETS/'source-ui-v3'
OVERRIDES = ASSETS/'source-ui-v4'
NEW_ICONS = ASSETS/'source-ui-v7'
REPLACEMENTS = {'shop':OVERRIDES/'supply-nav.png','rapid':OVERRIDES/'swift.png','hangar':NEW_ICONS/'hangar-matched-ratio.png','trainNav':ASSETS/'source-ui-v5/train-front.png'}
CELL = 96
manifest = {'cell': CELL, 'columns': 8, 'rows': 5, 'icons': {}}
canvas = Image.new('RGBA', (CELL*8, CELL*5))

def icon(name, im):
    i = len(manifest['icons'])
    if name in REPLACEMENTS: im = Image.open(REPLACEMENTS[name])
    im = im.convert('RGBA')
    # Ignore almost transparent halos when finding bounds; retain alpha in output.
    bbox = im.getchannel('A').point(lambda a: 255 if a > 16 else 0).getbbox()
    if not bbox: raise ValueError(name)
    im = im.crop(bbox)
    im.thumbnail((CELL-12, CELL-12), Image.Resampling.LANCZOS)
    x,y = (i%8)*CELL, (i//8)*CELL
    canvas.alpha_composite(im,(x+(CELL-im.width)//2,y+(CELL-im.height)//2))
    manifest['icons'][name] = {'column':i%8,'row':i//8}

for name in ['shop','train','research','settings']:
    icon(name,Image.open(SOURCE/f'{name}.png'))

def pack_grid(file,names):
    im=Image.open(SOURCE/file)
    # ImageGen grid spacing is approximate. Inspected alpha bounds avoid clipping
    # the lightning/cutter tips that cross nominal 4x4 cell boundaries.
    boxes = {
      'equipment.png':[(35,51,298,314),(339,52,603,312),(679,37,870,321),(917,67,1235,313),
        (27,374,324,620),(334,440,623,620),(632,338,917,624),(924,373,1230,624),
        (36,656,314,902),(332,661,624,886),(620,651,933,907),(970,637,1213,924),
        (53,907,286,1208),(321,946,612,1178),(627,915,915,1202),(942,937,1238,1194)],
      'actions.png':[(48,20,290,311),(353,20,596,311),(632,39,911,314),(946,18,1219,321),
        (41,337,311,613),(346,337,598,622),(630,344,918,625),(962,345,1207,609),
        (65,658,271,884),(349,646,595,889),(672,645,855,897),(950,640,1216,898),
        (29,917,307,1192),(319,929,622,1190),(654,908,920,1196),(957,924,1217,1185)]
    }
    for name, box in zip(names,boxes[file]):
        icon(name,im.crop(box))
pack_grid('equipment.png',['scrap','components','data','supply','pointDefense','storage','radar','repair','rapid','piercing','missile','incendiary','chain','ricochet','blades','scatter'])
pack_grid('actions.png',['scavenger','fragile','pressure','armor','wrench','shield','magnet','upgrade','pause','fullscreen','back','reroll','pulse','battle','cluster','split'])
icon('hangar',Image.open(SOURCE/'train.png'))
icon('trainNav',Image.open(ASSETS/'source-ui-v5/train-front.png'))
canvas.save(ASSETS/'ui-mobile-v7.webp',quality=84,method=6)
manifest['bytes']=(ASSETS/'ui-mobile-v7.webp').stat().st_size
(ASSETS/'ui-mobile-v7.json').write_text(json.dumps(manifest,indent=2)+'\n')
# Common normalized positions permit different CSS display sizes, preserving 6px gutters.
css=['/* Generated by scripts/pack-ui-v7.py. 96px source cells, 6px transparent gutters. */', '.ui-icon { background-image:url("assets/ui-mobile-v7.webp"); background-size:800% 500%; background-position:var(--icon-x,0%) var(--icon-y,0%); }']
for name,pos in manifest['icons'].items():
    css.append('.ui-icon--'+name+' { --icon-x:'+str(round(pos['column']/7*100,6))+'%; --icon-y:'+str(pos['row']/4*100)+'%; }')
# CSS aliases consume the same real asset; never substitute emoji or glyph art.
alias={'volatile':'incendiary','railgun':'piercing','cargo':'storage','repair':'wrench','overclock':'upgrade','dust':'scavenger','sprint':'battle','freight':'storage','heavy':'missile','focus':'piercing'}
selectors={name:name for name in manifest['icons']};selectors.update(alias)
for kind in ['weapon','icon']:
    for name,target in selectors.items():
        p=manifest['icons'][target]
        css.append(f'.overlay.selection-screen .selection-terminal .upgrade-card[data-{kind}="{name}"] .upgrade-icon {{ background-image:url("assets/ui-mobile-v7.webp"); background-size:800% 500%; background-position:{p["column"]/7*100:.6f}% {p["row"]/4*100:g}%; }}')
p=manifest['icons']['hangar']
css.append(f'.overlay.selection-screen .selection-terminal .upgrade-card[data-weapon="wingman"] .upgrade-icon {{background-image:url("assets/ui-mobile-v7.webp");background-size:800% 500%;background-position:{p["column"]/7*100:.6f}% {p["row"]/4*100:g}%;}}')
# Scope combat CSS as strongly as existing icon sheet rules.
for selector,name in [('.mission-launch .primary-button::before','battle'),('#app .pause-button::before','pause'),('#app .fullscreen-button::before','fullscreen'),('.reroll-button::before','reroll'),('.inspect-arrows button::before','back'),('.inspect-page-nav button::before','back'),('#app .skill-rail .claim-upgrade::before','upgrade'),('.levelup-screen .level-health > span','train'),('.home-settings-actions #startFullscreenButton > span','fullscreen')]:
    p=manifest['icons'][name]
    css.append(f'{selector} {{background-image:url("assets/ui-mobile-v7.webp");background-size:800% 500%;background-position:{p["column"]/7*100:.6f}% {p["row"]/4*100:g}%;}}')
(ROOT/'endless-rails/mobile-icons.css').write_text('\n'.join(css)+'\n')
regions=Image.open(SOURCE/'regions.png').convert('RGB')
thumbs=Image.new('RGB',(256*4,144))
for i,name in enumerate(['wasteland','ruins','industrial','infection']):
    x,y=i%2,i//2
    im=regions.crop((round(x*regions.width/2),round(y*regions.height/2),round((x+1)*regions.width/2),round((y+1)*regions.height/2)))
    im.resize((768,432),Image.Resampling.LANCZOS).save(ASSETS/f'hero-{name}-v3.webp',quality=78,method=6)
    thumbs.paste(im.resize((256,144),Image.Resampling.LANCZOS),(i*256,0))
thumbs.save(ASSETS/'regions-mobile-v3.webp',quality=78,method=6)
print(json.dumps({'atlasBytes':manifest['bytes'],'runtimeBytes':sum(p.stat().st_size for p in ASSETS.glob('*v3.webp') if p.name.startswith(('ui-mobile','hero-','regions-mobile'))),'icons':len(manifest['icons'])}))
